"""time

Revision ID: 57d5c5063751
Revises: 72d17f8afed5
Create Date: 2016-10-16 16:55:39.729226

"""

# revision identifiers, used by Alembic.
revision = '57d5c5063751'
down_revision = '72d17f8afed5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('register_time', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_register_time'), 'users', ['register_time'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_register_time'), table_name='users')
    op.drop_column('users', 'register_time')
    ### end Alembic commands ###
