"""init

Revision ID: 80202255b813
Revises: None
Create Date: 2018-10-09 17:11:52.895920

"""

# revision identifiers, used by Alembic.
import sqlalchemy as sa
from alembic import op

revision = '80202255b813'
down_revision = None


def upgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.create_table('categorys',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=20), nullable=False),
                    sa.Column('email', sa.String(length=60), nullable=False),
                    sa.Column('passwd_hash', sa.String(length=128), nullable=True),
                    sa.Column('register_time', sa.DateTime(), nullable=True),
                    sa.Column('last_seen', sa.DateTime(), nullable=True),
                    sa.Column('confirmed', sa.Boolean(), nullable=True),
                    sa.Column('about_me', sa.Text(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_register_time'), 'users', ['register_time'], unique=False)
    op.create_table('posts',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=64), nullable=True),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('body_html', sa.Text(), nullable=True),
                    sa.Column('create_time', sa.DateTime(), nullable=True),
                    sa.Column('read_count', sa.Integer(), nullable=True),
                    sa.Column('private', sa.Boolean(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_posts_create_time'), 'posts', ['create_time'], unique=False)
    op.create_table('comments',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('body', sa.Text(), nullable=True),
                    sa.Column('body_html', sa.Text(), nullable=True),
                    sa.Column('create_time', sa.DateTime(), nullable=True),
                    sa.Column('author_id', sa.Integer(), nullable=True),
                    sa.Column('post_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_comments_create_time'), 'comments', ['create_time'], unique=False)
    op.create_table('registrations',
                    sa.Column('post_id', sa.Integer(), nullable=True),
                    sa.Column('category_id.id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['category_id.id'], ['categorys.id'], ),
                    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], )
                    )
    # end Alembic commands ###


def downgrade():
    # commands auto generated by Alembic - please adjust! ###
    op.drop_table('registrations')
    op.drop_index(op.f('ix_comments_create_time'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_posts_create_time'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_users_register_time'), table_name='users')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('categorys')
    # end Alembic commands ###
