"""read_count

Revision ID: 8ac5e793eba6
Revises: 179fdc2b5037
Create Date: 2017-03-06 21:51:26.286293

"""

# revision identifiers, used by Alembic.
revision = '8ac5e793eba6'
down_revision = '179fdc2b5037'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('private', sa.Boolean(), nullable=True))
    op.add_column('posts', sa.Column('read_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'read_count')
    op.drop_column('posts', 'private')
    ### end Alembic commands ###
