"""mail

Revision ID: a0046002a6b2
Revises: 57d5c5063751
Create Date: 2016-10-16 22:26:01.928727

"""

# revision identifiers, used by Alembic.
revision = 'a0046002a6b2'
down_revision = '57d5c5063751'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
